import type { Metadata } from "next";

import "../styles/main.css"
import "../styles/login-sign-in.css"

export const metadata: Metadata = {
  title: "Ben Dover",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        {children}
      </body>
    </html>
  );
}
